# Configurations
title:            EMO-BON Data Management Book
longtitle:        EMO-BON Data Management Book
author:           VLIZ Open Science team
email:            opsci@vliz.be
description: >
  All documents related to the data management of the Emo-Bon project.

version:          1.0
gitbook_version:  3.2.3

url:              'https://https://data.emobon.embrc.eu/'
baseurl:          '/data-management-book'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   2

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
#permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  documentation:
    output: true
    permalink: /:path/
#  others:
#    output: true
#    permalink: /:collection/:path/

ordered_collections:
  - documentation
  #- others
  #- posts

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
